// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectManagement.DataAccess.Context;

namespace ProjectManagement.DataAccess.Migrations
{
    [DbContext(typeof(ProjectManagementDbContext))]
    [Migration("20220607075342_AddedDeveloperPhoneNumber")]
    partial class AddedDeveloperPhoneNumber
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectManagement.Domain.Models.Developer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("ProgrammingLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProgrammingLanguageId")
                        .IsUnique()
                        .HasFilter("[ProgrammingLanguageId] IS NOT NULL");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0287537-dfe1-4f44-8666-5da587651bf7"),
                            FirstName = "Larry",
                            LastName = "Page"
                        },
                        new
                        {
                            Id = new Guid("7b6bd555-c9f8-42a7-ac8f-698c2ba36646"),
                            FirstName = "Bill",
                            LastName = "Gates"
                        },
                        new
                        {
                            Id = new Guid("fb1459c7-393f-45b6-a662-dce000d9aac0"),
                            FirstName = "Mark",
                            LastName = "Zuckerberg"
                        },
                        new
                        {
                            Id = new Guid("08d38390-b579-40bc-8396-e355d52bc823"),
                            FirstName = "Ken",
                            LastName = "Thompson"
                        },
                        new
                        {
                            Id = new Guid("3aaaa471-54c9-4162-844d-9accf7a6ad80"),
                            FirstName = "Linus",
                            LastName = "Torvalds"
                        },
                        new
                        {
                            Id = new Guid("1ea74fc5-e844-4f70-b37f-ac2c9d6cb43c"),
                            FirstName = "Ada",
                            LastName = "Lovelace"
                        },
                        new
                        {
                            Id = new Guid("0bcd05a8-f538-48f1-a1d2-382f5e949c11"),
                            FirstName = "Alan",
                            LastName = "Turing"
                        });
                });

            modelBuilder.Entity("ProjectManagement.Domain.Models.DeveloperPhoneNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.ToTable("DeveloperPhoneNumbers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f48fbfb5-1e58-4937-85dd-f7a8e853f605"),
                            DeveloperId = new Guid("b0287537-dfe1-4f44-8666-5da587651bf7"),
                            Number = "+51 123-45-67"
                        });
                });

            modelBuilder.Entity("ProjectManagement.Domain.Models.ProgrammingLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ProgrammingLanguages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e075df46-8637-4395-866a-8e322ba6663c"),
                            Name = "Python"
                        },
                        new
                        {
                            Id = new Guid("2fcf3a18-54dd-4bb2-99a7-edc79052585a"),
                            Name = "Java"
                        },
                        new
                        {
                            Id = new Guid("0065a6c7-4140-4cc1-b0ec-71ba82894fe3"),
                            Name = "Ruby"
                        },
                        new
                        {
                            Id = new Guid("749856eb-7f8a-47e5-bd1c-f6ab09502d99"),
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("96118808-4bca-4299-9195-f655c019e5ac"),
                            Name = "C++"
                        },
                        new
                        {
                            Id = new Guid("18fd93eb-1cc6-4297-8cf5-92730e25cd81"),
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = new Guid("8697765d-ff50-415c-866f-696b23f6cea5"),
                            Name = "Go"
                        });
                });

            modelBuilder.Entity("ProjectManagement.Domain.Models.Developer", b =>
                {
                    b.HasOne("ProjectManagement.Domain.Models.ProgrammingLanguage", "FavoriteLanguage")
                        .WithOne()
                        .HasForeignKey("ProjectManagement.Domain.Models.Developer", "ProgrammingLanguageId")
                        .HasConstraintName("FK_Developer_ProgrammingLanguage_ProgrammingLanguageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("FavoriteLanguage");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Models.DeveloperPhoneNumber", b =>
                {
                    b.HasOne("ProjectManagement.Domain.Models.Developer", "Developer")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("DeveloperId")
                        .HasConstraintName("FK_DeveloperPhoneNumber_Developer_DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Models.Developer", b =>
                {
                    b.Navigation("PhoneNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
