// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectManagement.DataAccess.Context;

namespace ProjectManagement.DataAccess.Migrations
{
    [DbContext(typeof(ProjectManagementDbContext))]
    [Migration("20220312115833_SeedingItemsDataBase")]
    partial class SeedingItemsDataBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectManagement.Domain.Models.Developer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0287537-dfe1-4f44-8666-5da587651bf7"),
                            FirstName = "Larry",
                            LastName = "Page"
                        },
                        new
                        {
                            Id = new Guid("7b6bd555-c9f8-42a7-ac8f-698c2ba36646"),
                            FirstName = "Bill",
                            LastName = "Gates"
                        },
                        new
                        {
                            Id = new Guid("fb1459c7-393f-45b6-a662-dce000d9aac0"),
                            FirstName = "Mark",
                            LastName = "Zuckerberg"
                        },
                        new
                        {
                            Id = new Guid("08d38390-b579-40bc-8396-e355d52bc823"),
                            FirstName = "Ken",
                            LastName = "Thompson"
                        },
                        new
                        {
                            Id = new Guid("3aaaa471-54c9-4162-844d-9accf7a6ad80"),
                            FirstName = "Linus",
                            LastName = "Torvalds"
                        },
                        new
                        {
                            Id = new Guid("1ea74fc5-e844-4f70-b37f-ac2c9d6cb43c"),
                            FirstName = "Ada",
                            LastName = "Lovelace"
                        },
                        new
                        {
                            Id = new Guid("0bcd05a8-f538-48f1-a1d2-382f5e949c11"),
                            FirstName = "Alan",
                            LastName = "Turing"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
